version = 1

# Java analyzer
[[analyzers]]
name = "java"
enabled = true
  [analyzers.meta]
  runtime_version = "17"
  build_command = "mvn clean compile"

# Optional YAML analyzer for Mule XML/YAML configs
[[analyzers]]
name = "yaml"
enabled = true

# Auto-formatting transformer for Java
[[transformers]]
name = "java-format"
enabled = true

# Ignore unnecessary directories
ignore_patterns = [
    "exchange-docs/*",
    "target/*"
]
