version = 1

# Java analyzer for your Mule project
[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "17"   # Java 17
  build_command = "mvn clean compile"  # optional, helps with analysis

# Optional: YAML analyzer for Mule config files
[[analyzers]]
name = "yaml"
enabled = true

# Optional: auto-formatting transformer for Java code
[[transformers]]
name = "java-format"
enabled = true

# Optional: ignore certain directories (example)
ignore_patterns = [
    "exchange-docs/*",
    "target/*"
]
