version = 1

# Java analyzer
[[analyzers]]
name = "java"
enabled = true
  [analyzers.meta]
  runtime_version = "17"
  paths = ["src"]
  build_command = "mvn clean compile"

# Ignore unnecessary directories
ignore_patterns = [
    "exchange-docs/*",
    "target/*"
]
