version = 1

# Java analyzer for Mule project
[[analyzers]]
name = "java"
enabled = true
  [analyzers.meta]
  runtime_version = "17"
  # Source folder for Java/Mule modules
  paths = ["src"]
  build_command = "mvn clean compile"

# YAML/XML analyzer for Mule configuration files
[[analyzers]]
name = "yaml"
enabled = true
  [analyzers.meta]
  paths = ["src/main/mule"]

# Optional: Auto-formatting for Java code
[[transformers]]
name = "java-format"
enabled = true

# Ignore unnecessary or generated folders
ignore_patterns = [
    "exchange-docs/*",
    "target/*",
    ".github/*"
]
